name: productivity_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.3
  icons_flutter: ^0.0.5
  intl: ^0.20.2
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  http: ^1.6.0
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # ✅ Assets correctement placés ici
  assets:
    - assets/images/
    - assets/